### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by temospena** [U-Shift/EITcourse#6]
- [x] GTFS section in `open-data.qmd`
- [x] convert the needed scripts with `knitr::purl("file.qmd", "code/file.qmd", documentation = 0)` or 1 or 2.
- [x] add e-scooter data in releases
- [x] prepare software usb
- [x] put book pdf also in releases
